//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("foodAppModel", "FK_restuarant_tag_Restuarant", "Restuarant", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(foodApp.Models.Restuarant), "restuarant_tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(foodApp.Models.restuarant_tag), true)]
[assembly: EdmRelationshipAttribute("foodAppModel", "FK_Resturant_food_Restuarant", "Restuarant", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(foodApp.Models.Restuarant), "Resturant_food", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(foodApp.Models.Resturant_food), true)]
[assembly: EdmRelationshipAttribute("foodAppModel", "FK_user_food_Restuarant", "Restuarant", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(foodApp.Models.Restuarant), "user_food", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(foodApp.Models.user_food), true)]
[assembly: EdmRelationshipAttribute("foodAppModel", "FK_user_rest_Restuarant", "Restuarant", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(foodApp.Models.Restuarant), "user_rest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(foodApp.Models.user_rest), true)]
[assembly: EdmRelationshipAttribute("foodAppModel", "FK_user_food_Resturant_food1", "Resturant_food", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(foodApp.Models.Resturant_food), "user_food", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(foodApp.Models.user_food), true)]
[assembly: EdmRelationshipAttribute("foodAppModel", "FK_user_food_User_acc1", "User_acc", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(foodApp.Models.User_acc), "user_food", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(foodApp.Models.user_food), true)]
[assembly: EdmRelationshipAttribute("foodAppModel", "FK_user_rest_User_acc", "User_acc", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(foodApp.Models.User_acc), "user_rest", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(foodApp.Models.user_rest), true)]

#endregion

namespace foodApp.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class foodAppEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new foodAppEntities object using the connection string found in the 'foodAppEntities' section of the application configuration file.
        /// </summary>
        public foodAppEntities() : base("name=foodAppEntities", "foodAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new foodAppEntities object.
        /// </summary>
        public foodAppEntities(string connectionString) : base(connectionString, "foodAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new foodAppEntities object.
        /// </summary>
        public foodAppEntities(EntityConnection connection) : base(connection, "foodAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Restuarant> Restuarants
        {
            get
            {
                if ((_Restuarants == null))
                {
                    _Restuarants = base.CreateObjectSet<Restuarant>("Restuarants");
                }
                return _Restuarants;
            }
        }
        private ObjectSet<Restuarant> _Restuarants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<restuarant_tag> restuarant_tag
        {
            get
            {
                if ((_restuarant_tag == null))
                {
                    _restuarant_tag = base.CreateObjectSet<restuarant_tag>("restuarant_tag");
                }
                return _restuarant_tag;
            }
        }
        private ObjectSet<restuarant_tag> _restuarant_tag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Resturant_food> Resturant_food
        {
            get
            {
                if ((_Resturant_food == null))
                {
                    _Resturant_food = base.CreateObjectSet<Resturant_food>("Resturant_food");
                }
                return _Resturant_food;
            }
        }
        private ObjectSet<Resturant_food> _Resturant_food;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User_acc> User_acc
        {
            get
            {
                if ((_User_acc == null))
                {
                    _User_acc = base.CreateObjectSet<User_acc>("User_acc");
                }
                return _User_acc;
            }
        }
        private ObjectSet<User_acc> _User_acc;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user_food> user_food
        {
            get
            {
                if ((_user_food == null))
                {
                    _user_food = base.CreateObjectSet<user_food>("user_food");
                }
                return _user_food;
            }
        }
        private ObjectSet<user_food> _user_food;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user_rest> user_rest
        {
            get
            {
                if ((_user_rest == null))
                {
                    _user_rest = base.CreateObjectSet<user_rest>("user_rest");
                }
                return _user_rest;
            }
        }
        private ObjectSet<user_rest> _user_rest;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Restuarants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRestuarants(Restuarant restuarant)
        {
            base.AddObject("Restuarants", restuarant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the restuarant_tag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorestuarant_tag(restuarant_tag restuarant_tag)
        {
            base.AddObject("restuarant_tag", restuarant_tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Resturant_food EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResturant_food(Resturant_food resturant_food)
        {
            base.AddObject("Resturant_food", resturant_food);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User_acc EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser_acc(User_acc user_acc)
        {
            base.AddObject("User_acc", user_acc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user_food EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser_food(user_food user_food)
        {
            base.AddObject("user_food", user_food);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user_rest EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser_rest(user_rest user_rest)
        {
            base.AddObject("user_rest", user_rest);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodAppModel", Name="Restuarant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Restuarant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Restuarant object.
        /// </summary>
        /// <param name="rID">Initial value of the RID property.</param>
        public static Restuarant CreateRestuarant(global::System.Guid rID)
        {
            Restuarant restuarant = new Restuarant();
            restuarant.RID = rID;
            return restuarant;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RID
        {
            get
            {
                return _RID;
            }
            set
            {
                if (_RID != value)
                {
                    OnRIDChanging(value);
                    ReportPropertyChanging("RID");
                    _RID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RID");
                    OnRIDChanged();
                }
            }
        }
        private global::System.Guid _RID;
        partial void OnRIDChanging(global::System.Guid value);
        partial void OnRIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Resturant_name
        {
            get
            {
                return _Resturant_name;
            }
            set
            {
                OnResturant_nameChanging(value);
                ReportPropertyChanging("Resturant_name");
                _Resturant_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Resturant_name");
                OnResturant_nameChanged();
            }
        }
        private global::System.String _Resturant_name;
        partial void OnResturant_nameChanging(global::System.String value);
        partial void OnResturant_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> average_rating
        {
            get
            {
                return _average_rating;
            }
            set
            {
                Onaverage_ratingChanging(value);
                ReportPropertyChanging("average_rating");
                _average_rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("average_rating");
                Onaverage_ratingChanged();
            }
        }
        private Nullable<global::System.Double> _average_rating;
        partial void Onaverage_ratingChanging(Nullable<global::System.Double> value);
        partial void Onaverage_ratingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_restuarant_tag_Restuarant", "restuarant_tag")]
        public EntityCollection<restuarant_tag> restuarant_tag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<restuarant_tag>("foodAppModel.FK_restuarant_tag_Restuarant", "restuarant_tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<restuarant_tag>("foodAppModel.FK_restuarant_tag_Restuarant", "restuarant_tag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_Resturant_food_Restuarant", "Resturant_food")]
        public EntityCollection<Resturant_food> Resturant_food
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Resturant_food>("foodAppModel.FK_Resturant_food_Restuarant", "Resturant_food");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Resturant_food>("foodAppModel.FK_Resturant_food_Restuarant", "Resturant_food", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_food_Restuarant", "user_food")]
        public EntityCollection<user_food> user_food
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_food>("foodAppModel.FK_user_food_Restuarant", "user_food");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_food>("foodAppModel.FK_user_food_Restuarant", "user_food", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_rest_Restuarant", "user_rest")]
        public EntityCollection<user_rest> user_rest
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_rest>("foodAppModel.FK_user_rest_Restuarant", "user_rest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_rest>("foodAppModel.FK_user_rest_Restuarant", "user_rest", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodAppModel", Name="restuarant_tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class restuarant_tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new restuarant_tag object.
        /// </summary>
        /// <param name="rID">Initial value of the RID property.</param>
        /// <param name="tag">Initial value of the tag property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static restuarant_tag Createrestuarant_tag(global::System.Guid rID, global::System.String tag, global::System.Guid id)
        {
            restuarant_tag restuarant_tag = new restuarant_tag();
            restuarant_tag.RID = rID;
            restuarant_tag.tag = tag;
            restuarant_tag.ID = id;
            return restuarant_tag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RID
        {
            get
            {
                return _RID;
            }
            set
            {
                OnRIDChanging(value);
                ReportPropertyChanging("RID");
                _RID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RID");
                OnRIDChanged();
            }
        }
        private global::System.Guid _RID;
        partial void OnRIDChanging(global::System.Guid value);
        partial void OnRIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tag
        {
            get
            {
                return _tag;
            }
            set
            {
                OntagChanging(value);
                ReportPropertyChanging("tag");
                _tag = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tag");
                OntagChanged();
            }
        }
        private global::System.String _tag;
        partial void OntagChanging(global::System.String value);
        partial void OntagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_restuarant_tag_Restuarant", "Restuarant")]
        public Restuarant Restuarant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_restuarant_tag_Restuarant", "Restuarant").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_restuarant_tag_Restuarant", "Restuarant").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Restuarant> RestuarantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_restuarant_tag_Restuarant", "Restuarant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Restuarant>("foodAppModel.FK_restuarant_tag_Restuarant", "Restuarant", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodAppModel", Name="Resturant_food")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Resturant_food : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Resturant_food object.
        /// </summary>
        /// <param name="rID">Initial value of the RID property.</param>
        /// <param name="fID">Initial value of the FID property.</param>
        public static Resturant_food CreateResturant_food(global::System.Guid rID, global::System.Guid fID)
        {
            Resturant_food resturant_food = new Resturant_food();
            resturant_food.RID = rID;
            resturant_food.FID = fID;
            return resturant_food;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RID
        {
            get
            {
                return _RID;
            }
            set
            {
                OnRIDChanging(value);
                ReportPropertyChanging("RID");
                _RID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RID");
                OnRIDChanged();
            }
        }
        private global::System.Guid _RID;
        partial void OnRIDChanging(global::System.Guid value);
        partial void OnRIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid FID
        {
            get
            {
                return _FID;
            }
            set
            {
                if (_FID != value)
                {
                    OnFIDChanging(value);
                    ReportPropertyChanging("FID");
                    _FID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FID");
                    OnFIDChanged();
                }
            }
        }
        private global::System.Guid _FID;
        partial void OnFIDChanging(global::System.Guid value);
        partial void OnFIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String food
        {
            get
            {
                return _food;
            }
            set
            {
                OnfoodChanging(value);
                ReportPropertyChanging("food");
                _food = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("food");
                OnfoodChanged();
            }
        }
        private global::System.String _food;
        partial void OnfoodChanging(global::System.String value);
        partial void OnfoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> spicy_rating
        {
            get
            {
                return _spicy_rating;
            }
            set
            {
                Onspicy_ratingChanging(value);
                ReportPropertyChanging("spicy_rating");
                _spicy_rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("spicy_rating");
                Onspicy_ratingChanged();
            }
        }
        private Nullable<global::System.Int32> _spicy_rating;
        partial void Onspicy_ratingChanging(Nullable<global::System.Int32> value);
        partial void Onspicy_ratingChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_Resturant_food_Restuarant", "Restuarant")]
        public Restuarant Restuarant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_Resturant_food_Restuarant", "Restuarant").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_Resturant_food_Restuarant", "Restuarant").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Restuarant> RestuarantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_Resturant_food_Restuarant", "Restuarant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Restuarant>("foodAppModel.FK_Resturant_food_Restuarant", "Restuarant", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_food_Resturant_food1", "user_food")]
        public EntityCollection<user_food> user_food
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_food>("foodAppModel.FK_user_food_Resturant_food1", "user_food");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_food>("foodAppModel.FK_user_food_Resturant_food1", "user_food", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodAppModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodAppModel", Name="User_acc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_acc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User_acc object.
        /// </summary>
        /// <param name="number">Initial value of the number property.</param>
        public static User_acc CreateUser_acc(global::System.Int32 number)
        {
            User_acc user_acc = new User_acc();
            user_acc.number = number;
            return user_acc;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 number
        {
            get
            {
                return _number;
            }
            set
            {
                if (_number != value)
                {
                    OnnumberChanging(value);
                    ReportPropertyChanging("number");
                    _number = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("number");
                    OnnumberChanged();
                }
            }
        }
        private global::System.Int32 _number;
        partial void OnnumberChanging(global::System.Int32 value);
        partial void OnnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_food_User_acc1", "user_food")]
        public EntityCollection<user_food> user_food
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_food>("foodAppModel.FK_user_food_User_acc1", "user_food");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_food>("foodAppModel.FK_user_food_User_acc1", "user_food", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_rest_User_acc", "user_rest")]
        public EntityCollection<user_rest> user_rest
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_rest>("foodAppModel.FK_user_rest_User_acc", "user_rest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_rest>("foodAppModel.FK_user_rest_User_acc", "user_rest", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodAppModel", Name="user_food")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_food : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user_food object.
        /// </summary>
        /// <param name="number">Initial value of the number property.</param>
        /// <param name="rID">Initial value of the RID property.</param>
        /// <param name="uFID">Initial value of the UFID property.</param>
        public static user_food Createuser_food(global::System.Int32 number, global::System.Guid rID, global::System.Guid uFID)
        {
            user_food user_food = new user_food();
            user_food.number = number;
            user_food.RID = rID;
            user_food.UFID = uFID;
            return user_food;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 number
        {
            get
            {
                return _number;
            }
            set
            {
                OnnumberChanging(value);
                ReportPropertyChanging("number");
                _number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("number");
                OnnumberChanged();
            }
        }
        private global::System.Int32 _number;
        partial void OnnumberChanging(global::System.Int32 value);
        partial void OnnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> FID
        {
            get
            {
                return _FID;
            }
            set
            {
                OnFIDChanging(value);
                ReportPropertyChanging("FID");
                _FID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FID");
                OnFIDChanged();
            }
        }
        private Nullable<global::System.Guid> _FID;
        partial void OnFIDChanging(Nullable<global::System.Guid> value);
        partial void OnFIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> rating
        {
            get
            {
                return _rating;
            }
            set
            {
                OnratingChanging(value);
                ReportPropertyChanging("rating");
                _rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rating");
                OnratingChanged();
            }
        }
        private Nullable<global::System.Double> _rating;
        partial void OnratingChanging(Nullable<global::System.Double> value);
        partial void OnratingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String review
        {
            get
            {
                return _review;
            }
            set
            {
                OnreviewChanging(value);
                ReportPropertyChanging("review");
                _review = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("review");
                OnreviewChanged();
            }
        }
        private global::System.String _review;
        partial void OnreviewChanging(global::System.String value);
        partial void OnreviewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RID
        {
            get
            {
                return _RID;
            }
            set
            {
                OnRIDChanging(value);
                ReportPropertyChanging("RID");
                _RID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RID");
                OnRIDChanged();
            }
        }
        private global::System.Guid _RID;
        partial void OnRIDChanging(global::System.Guid value);
        partial void OnRIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UFID
        {
            get
            {
                return _UFID;
            }
            set
            {
                if (_UFID != value)
                {
                    OnUFIDChanging(value);
                    ReportPropertyChanging("UFID");
                    _UFID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UFID");
                    OnUFIDChanged();
                }
            }
        }
        private global::System.Guid _UFID;
        partial void OnUFIDChanging(global::System.Guid value);
        partial void OnUFIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_food_Restuarant", "Restuarant")]
        public Restuarant Restuarant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_user_food_Restuarant", "Restuarant").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_user_food_Restuarant", "Restuarant").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Restuarant> RestuarantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_user_food_Restuarant", "Restuarant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Restuarant>("foodAppModel.FK_user_food_Restuarant", "Restuarant", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_food_Resturant_food1", "Resturant_food")]
        public Resturant_food Resturant_food
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resturant_food>("foodAppModel.FK_user_food_Resturant_food1", "Resturant_food").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resturant_food>("foodAppModel.FK_user_food_Resturant_food1", "Resturant_food").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Resturant_food> Resturant_foodReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Resturant_food>("foodAppModel.FK_user_food_Resturant_food1", "Resturant_food");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Resturant_food>("foodAppModel.FK_user_food_Resturant_food1", "Resturant_food", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_food_User_acc1", "User_acc")]
        public User_acc User_acc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_acc>("foodAppModel.FK_user_food_User_acc1", "User_acc").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_acc>("foodAppModel.FK_user_food_User_acc1", "User_acc").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User_acc> User_accReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_acc>("foodAppModel.FK_user_food_User_acc1", "User_acc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User_acc>("foodAppModel.FK_user_food_User_acc1", "User_acc", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="foodAppModel", Name="user_rest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_rest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user_rest object.
        /// </summary>
        /// <param name="number">Initial value of the number property.</param>
        /// <param name="uRID">Initial value of the URID property.</param>
        public static user_rest Createuser_rest(global::System.Int32 number, global::System.Guid uRID)
        {
            user_rest user_rest = new user_rest();
            user_rest.number = number;
            user_rest.URID = uRID;
            return user_rest;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 number
        {
            get
            {
                return _number;
            }
            set
            {
                OnnumberChanging(value);
                ReportPropertyChanging("number");
                _number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("number");
                OnnumberChanged();
            }
        }
        private global::System.Int32 _number;
        partial void OnnumberChanging(global::System.Int32 value);
        partial void OnnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> RID
        {
            get
            {
                return _RID;
            }
            set
            {
                OnRIDChanging(value);
                ReportPropertyChanging("RID");
                _RID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RID");
                OnRIDChanged();
            }
        }
        private Nullable<global::System.Guid> _RID;
        partial void OnRIDChanging(Nullable<global::System.Guid> value);
        partial void OnRIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> rating
        {
            get
            {
                return _rating;
            }
            set
            {
                OnratingChanging(value);
                ReportPropertyChanging("rating");
                _rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rating");
                OnratingChanged();
            }
        }
        private Nullable<global::System.Double> _rating;
        partial void OnratingChanging(Nullable<global::System.Double> value);
        partial void OnratingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String review
        {
            get
            {
                return _review;
            }
            set
            {
                OnreviewChanging(value);
                ReportPropertyChanging("review");
                _review = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("review");
                OnreviewChanged();
            }
        }
        private global::System.String _review;
        partial void OnreviewChanging(global::System.String value);
        partial void OnreviewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid URID
        {
            get
            {
                return _URID;
            }
            set
            {
                if (_URID != value)
                {
                    OnURIDChanging(value);
                    ReportPropertyChanging("URID");
                    _URID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("URID");
                    OnURIDChanged();
                }
            }
        }
        private global::System.Guid _URID;
        partial void OnURIDChanging(global::System.Guid value);
        partial void OnURIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_rest_Restuarant", "Restuarant")]
        public Restuarant Restuarant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_user_rest_Restuarant", "Restuarant").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_user_rest_Restuarant", "Restuarant").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Restuarant> RestuarantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restuarant>("foodAppModel.FK_user_rest_Restuarant", "Restuarant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Restuarant>("foodAppModel.FK_user_rest_Restuarant", "Restuarant", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("foodAppModel", "FK_user_rest_User_acc", "User_acc")]
        public User_acc User_acc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_acc>("foodAppModel.FK_user_rest_User_acc", "User_acc").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_acc>("foodAppModel.FK_user_rest_User_acc", "User_acc").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User_acc> User_accReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_acc>("foodAppModel.FK_user_rest_User_acc", "User_acc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User_acc>("foodAppModel.FK_user_rest_User_acc", "User_acc", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
